sudo: false
language: elixir
elixir:
  - 1.0.2
services:
  - elasticsearch
notifications:
  email: false
  slack:
    rooms:
      - goroundscope:3uAcoRPk3TZkvMXJTCEcQYS7#oss-feed
    on_success: change
