sudo: required
language: elixir

elixir:
  - 1.7.4

matrix:
  include:
    - elixir '1.7.4'
    - otp_release '20.0'

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.2.deb
  - sudo service elasticsearch start
  # - wget -nv --tries 4 --retry-connrefused --no-check-certificate 127.0.0.1:9200
