sudo: required
language: elixir

services:
  - elasticsearch

before_script:
  - sleep 10

elixir:
  - 1.3.0
  - 1.4.1

notifications:
  email: false
  slack:
    rooms:
      - zatvobor:eLjCTZD2l85xl19hsSdxkMdN##oss-feed
    on_success: change
