language: erlang
notifications:
  recipients:
    - a.zatvornitskiy@gmail.com
    - opak.alexandr@gmail.com
otp_release:
  - R15B
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
